oauth2/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/ImpersonatingTokenExchangeFlowTest.java
The `resolvedTokenEndpoint` test should have been removed as it doesn't make sense anymore after #25.
=> Clean up impersonation flow tests

oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/OAuth2Properties.java
The javadocs of properties related to impersonation weren't properly updated after #25. This PR fixes that.
=> OAuth2Properties: fix impersonation javadocs

.github/workflows/gradle.yml, gradle/libs.versions.toml, settings.gradle.kts
Using the available snapshots simplifies CI. Once the 1.9.0 release is out, we can get rid of the Apache maven repo.
=> Build: temporarily use Iceberg 1.9.0-SNAPSHOT

oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/OAuth2Manager.java, oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/OAuth2Session.java, oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2Agent.java, oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/config/BasicConfig.java, oauth2/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/FlowContextFactory.java, oauth2/src/test/java/com/dremio/iceberg/authmgr/oauth2/OAuth2ManagerTest.java, oauth2/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/TestEnvironment.java
The catalog session was keeping the init `HTTPClient` which was causing errors when refreshing tokens since that `HTTPClient` is closed after the config endpoint is contacted.
=> Fix incorrect handling of init sessions

.github/workflows/ci.yml, .github/workflows/release.yml, build-logic/build.gradle.kts, build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts, build-logic/src/main/kotlin/authmgr-maven.gradle.kts, build.gradle.kts, docs/README.md, docs/installation.md, docs/usage.md, gradle/baselibs.versions.toml, oauth2/build.gradle.kts, tools/immutables/build.gradle.kts
Fixes #12.
This change introduces the JReleaser Gradle plugin, which is used to deploy release artifacts to Maven Central and to generate a GitHub release.
It also introduces a new CI workflow to perform release tasks.
Note for reviewers: I thoroughly tested the release plugin & workflow on my own fork, using my own credentials and Sonatype account. I can say that everything works as expected there – which doesn't mean that they will work out of the box here. But at least I've sorted out the usual problems already.
=> feat(build): Add release workflow with JReleaser

build-logic/src/main/kotlin/authmgr-maven.gradle.kts, oauth2/runtime/build.gradle.kts
The authmgr-runtime pom includes a `<dependencies>` element containing a dependency to authmgr-core, which is wrong for the runtime-uber jar.
Fix is to use the `shadow` component instead of the `java` component in presence of the shadow plugin.
=> fix(runtime-pom): use the right component

oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/container/NessieContainer.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkNessieKeycloakS3IT.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkNessieS3ITBase.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkPolarisS3IT.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkPolarisS3ITBase.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkS3ITBase.java, oauth2/runtime-spark-tests/src/intTest/resources/logback-test.xml
This change adds a NessieContainer, then uses that container to add integration tests with Spark, Nessie and Keycloak, in order to exercise request signing.
=> feat(ci): Add integration tests for request signing

oauth2/core/build.gradle.kts, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/compat/PropertiesSanitizer.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/compat/LegacyPropertiesMigratorTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/compat/PropertiesSanitizerTest.java
As a general rule, the sanitizer should filter out sensitive information such as: usernames, passwords, secrets, private keys, etc.
But tokens are generally tolerated. In this regard, it is incorrect for the sanitizer to filter out subject and actor tokens.
This PR also introduces unit tests for both `LegacyPropertiesMigrator` and `PropertiesSanitizer`.
=> fix(oauth): PropertiesSanitizer should not filter out subject and actor tokens

.github/workflows/ci.yml
The Polaris Docker image only exists for linux/arm atm.
=> fix(ci): Temporarily use linux/arm images

oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/TokenExchangeFlowTest.java, oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/TestConstants.java, oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/expectation/AuthorizationCodeExpectation.java
Some tests were supposed to exercise "dynamic" subject and actor tokens, but due to misconfigurations, they weren't.
=> fix(oauth): Fix token exchange tests

.github/workflows/ci.yml, oauth2/core/build.gradle.kts, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentKeycloakLongIT.java, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentPolarisLongIT.java, oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/container/PolarisContainer.java, oauth2/runtime-flink-tests/build.gradle.kts, oauth2/runtime-spark-tests/build.gradle.kts
The CI builds started hanging a few days ago. I fear this could be related to the ARM runners, so let's revert the changes around Docker in CI to eliminate this possible culprit.
=> feat(ci): Split jobs & use temporary multi-platform Docker image

oauth2/core/build.gradle.kts
Unit tests seem to hang as well, trying to see if setting parallelism back to 1 makes things better.
=> fix(ci): Lower parallelism of unit tests

oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentKeycloakIT.java, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentKeycloakLongIT.java, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentLongITBase.java, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentPolarisIT.java, oauth2/core/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentPolarisLongIT.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2AgentTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/AuthorizationCodeFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/ClientCredentialsFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/DeviceCodeFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/IcebergClientCredentialsFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/IcebergRefreshTokenFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/PasswordFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/RefreshTokenFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/TokenExchangeFlowTest.java, oauth2/runtime-flink-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/flink/FlinkPolarisS3ITBase.java, oauth2/runtime-spark-tests/src/intTest/java/com/dremio/iceberg/authmgr/oauth2/test/spark/SparkS3ITBase.java
This change modifies all the tests that were calling `CompletableFuture.join()` out of convenience, since this method does not throw checked exceptions.
Unfortunately, `.join()` also masks any `InterruptedException` behind a `CompletionException`. This seems to interfere with JUnit's ability to properly interrupt a test after a timeout, at least on Linux.
=> fix(test): Use CompletableFuture.get() to avoid masking InterruptedExceptions

oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/agent/OAuth2Agent.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/AbstractFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/AuthorizationCodeFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/ClientCredentialsFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/DeviceCodeFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/Flow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/FlowFactory.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/IcebergRefreshTokenFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/InitialFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/PasswordFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/RefreshFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/RefreshTokenFlow.java, oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/flow/TokenExchangeFlow.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/AuthorizationCodeFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/DeviceCodeFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/IcebergClientCredentialsFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/IcebergRefreshTokenFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/PasswordFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/RefreshTokenFlowTest.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/flow/TokenExchangeFlowTest.java
This change is a pure refactor of the Flow API to make it more explicit about the usage of current tokens. There is no functional change.
=> chore(oauth): Refactor Flow API to distinguish initial vs refresh flows

oauth2/core/build.gradle.kts, oauth2/core/src/testFixtures/java/com/dremio/iceberg/authmgr/oauth2/test/server/UnitTestHttpServer.java, oauth2/core/src/testFixtures/resources/mockserver.properties
MockServer can create a surprising amount of threads. 
This change aims at reducing the memory and CPU footprint of MockServer by reducing the number of threads to the minimum and by reducing some limits. 
This change also introduces the ability to print MockServer memory stats in CSV.
=> feat(tests): Reduce memory and thread use of MockServer

.github/workflows/release.yml, build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts, gradle/baselibs.versions.toml
Writing to issues and discussions is currently not possible from the GitHub token that runs release jobs.
=> fix(release): Temporarily disable writes to issues and discussions

gradle/libs.versions.toml, oauth2/core/build.gradle.kts
With the switch to Nimbus, Jackson became unused.
=> chore(build): Remove Jackson dependency

oauth2/core/src/main/java/com/dremio/iceberg/authmgr/oauth2/config/ConfigSanitizer.java, oauth2/core/src/test/java/com/dremio/iceberg/authmgr/oauth2/config/ConfigSanitizerTest.java
These settings should only be set at catalog level as they usually cannot be modified later on.
=> feat(oauth): Forbid system & http settings in context and table sessions

build-logic/build.gradle.kts, build-logic/src/main/kotlin/authmgr-bundle.gradle.kts, build-logic/src/main/kotlin/authmgr-java.gradle.kts, gradle/baselibs.versions.toml, gradle/license/allowed-licenses.json5
Fixes #11.
Fixes #60.
This commit introduces the following changes:
- All non-shaded artifacts produced by the build now contain the project's license text under `META-INF/LICENSE`.
- All non-shaded artifacts produced by the build now contain the project's NOTICE file under `META-INF/NOTICE`.
- The `authmgr-oauth2-runtime` binary distribution uber-jar includes:
- A special `LICENSE` file including this project's license, followed by license mentions for all dependencies;
- A `NOTICE` file including the contents of this project's `NOTICE`, and all `NOTICE` and `NOTICE.txt` files from dependencies.
- The `com.github.jk1.dependency-license-report` plugin has been added in order to generate the extended `LICENSE` file for uber-jars.
=> feat(build): Generate distribution LICENSE and NOTICE files

build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts
This section is not necessary for artifacts already published by the Maven publication.
I manually verified the contents of the Sonatype upload zip by running `JRELEASER_DRY_RUN=true ./gradlew jreleaserFullRelease --info`.
=> fix(build): Remove unnecessary "files" section from JReleaser config

build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts
The `files` section is not required to deploy artifacts to Sonatype, but it is in fact required to define assets to include in the GitHub release.
This change partially reverts commit ea7d92096adc784f1bd606203b7fab33ba1ad594.
=> chore(build): Re-introduce the "files" section in JReleaser config

build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts, build-logic/src/main/kotlin/authmgr-maven.gradle.kts
The introduction of a new module recently (`authmgr-oauth2-tests`) broke the Maven publication & JReleaser logic. 
This PR changes the affected plugins, `authmgr-maven` and `authmgr-jreleaser`. Their logic has been simplified and doesn't require anymore to keep lists of projects to include or to exclude.
=> fix(build): Fix Maven publication & JReleaser configuration

build-logic/src/main/kotlin/authmgr-jreleaser.gradle.kts
The CI user doesn't have permissions for that.
This PR also shortens the release name (it didn't fit in the right panel on the repository landing page) and removes the unused `release.github.commitAuthor` section.
=> fix(build): Disable closing milestones during release
